### ISSUE TITLE
Refined sort facets

### ISSUE THREAD

**Issue by ColeDCrawford** [artshumrc/giza#145] opened 2021-03-03 15:42 UTC
E.g. for Objects: Classification, Material, Findspot, Owning Institution, Period, Date, etc. (Currently not operational.)

**Comment by rsinghal** [comment] 2021-03-03 16:01
duplicate of #138

**Comment by ColeDCrawford** [comment] 2021-03-03 16:21
Closing (duplicate)

**Closed** 2021-03-19 19:09 UTC
