### ISSUE TITLE
Stock photos for Giza@School landing

### ISSUE THREAD

**Issue by lukehollis** [artshumrc/giza#112] opened 2021-02-04 16:47 UTC
![Glossary_FAQ_container illustration](https://user-images.githubusercontent.com/2633382/106926089-9471ab80-66c5-11eb-95a3-8b969c1a3d3c.jpg)
![Glossary_FAQ_iStock-522259145-WebCrop3](https://user-images.githubusercontent.com/2633382/106926103-976c9c00-66c5-11eb-84d5-648d808dd06f.png)
![Lesson_Topics_iStock-1172281585-WebCrop](https://user-images.githubusercontent.com/2633382/106926106-98053280-66c5-11eb-8604-494dfc196282.png)

**Comment by lukehollis** [comment] 2021-02-11 17:38
"""
7) I bought the two iStock images, for the page with "Lesson Topics” (tall rectangle) and “Glossary and FAQ” (circular): http://giza-web2.rc.fas.harvard.edu/gizaatschool/

I’ll send those now to you separately, since they are large files. Luke, some appropriate cropping and downsizing will be needed to slot them in to the page.

--Awesome!  Thanks for getting them, Peter.  Luke, if you would like guidance on cropping, please let me know. 
"""

**Comment by rsinghal** [comment] 2021-02-16 20:34
duplicate of #104

**Comment by lukehollis** [comment] 2021-03-14 03:06
Similar to https://github.com/artshumrc/giza/issues/104 I believe this is ready for review to be closed, should've been included in this PR: #119

Can review at http://giza.fas.harvard.edu/gizaatschool/

**Closed** 2021-03-25 15:49 UTC
