### ISSUE TITLE
User ability to add media to MyGiza Collections

### ISSUE THREAD

**Issue by npicardo** [artshumrc/giza#131] opened 2021-02-16 17:44 UTC
There is no front-facing button or mechanism for users to select images to add to their MyGiza Collections.

**Comment by ColeDCrawford** [comment] 2021-03-03 15:18
Related to / duplicate of #90

**Comment by ColeDCrawford** [comment] 2021-03-03 16:24
Closing (duplicate)

**Closed by ColeDCrawford** 2021-03-03 16:24 UTC
